# Generated by Django 5.0.6 on 2024-07-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_exhibition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(default='https://youtube.com/shorts/8-hgPVs2udo?si=562aghtwobhB59Hw'),
        ),
    ]
