# Generated by Django 5.0.6 on 2024-07-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(default='https://res.cloudinary.com/dn7sk8y8y/video/upload/v1720029053/WhatsApp_Video_2024-07-03_at_23.15.49_34d932f7_rx0t8l.mp4 '),
        ),
    ]
